language: csharp
solution: EasyPeasy.sln

env:
    global:
        - EnableNuGetPackageRestore=true

install:
    - nuget restore EasyPeasy.sln
    - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory testrunner

script:
    - xbuild /p:Configuration=Release EasyPeasy.sln
    - mono ./testrunner/NUnit.Console.3.0.1/tools/nunit3-console.exe ./tests/EasyPeasy.Tests/bin/Release/EasyPeasy.Tests.dll
